import = [
  "~/.config/alacritty/themes/themes/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5

decorations = "Buttonless"
opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS NF"
size = 13
